# Generated by Django 3.2.4 on 2021-07-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledetail',
            name='profile_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
